### ISSUE TITLE
does not use .eslintrc.js file

### ISSUE THREAD

**Issue by joshua1** [TheSavior/ESLint-Formatter#10]
I have an .eslintrc.js file in my porject specifying that the airbnb style linter be used. but this is no way to condfigure this plugin to use such files within a project , is there?

**Comment by TheSavior** [comment]
One of the settings for the plugin is ```"config_path": "",```. Take a look at the README for more information on how that is used and how it is passed to eslint. Let me know if that isn't sufficient.

**Comment by joshua1** [comment]
I have used the ```"config_path":""``` still no dice. it doesn't do any formatting. Might be because my .eslintrc only contains extends property for airbnb style guide or what? 
``` module.exports = {
    "extends": ["airbnb","plugin:meteor/recommended"],
    "plugins": [
        "react",
        "meteor",
        "jsx-a11y"
    ],
};```

**Comment by TheSavior** [comment]
You set the `config_path` to `""`, or to the actual path of the file? What happens when you call eslint from the command line and pass the same value in `--config`?

**Comment by joshua1** [comment]
I set the config path to ```"config_path":"/.eslintrc.js"``` and from the command line passing the ```--config``` flag, it ran without issues. from my project root ```eslint . --config '.eslintrc.js'``` was teh command

**Comment by TheSavior** [comment]
What if you use an absolute path to your .eslintrc.js file as the `config_path`?

**Comment by Gecko222** [comment]
I have same issue.
