### ISSUE TITLE
If config_path must be an absolute path?

### ISSUE THREAD

**Issue by xwartz** [TheSavior/ESLint-Formatter#11]
I want to use different  `.eslintrc.js` file in my different project, but how to set `config_path`?

**Comment by TheSavior** [comment]
Per https://www.sublimetext.com/docs/3/settings.html you should be able to specify them in your project settings.

Relevant part of that page:

```
Settings files are consulted in this order:

Packages/Default/Preferences.sublime-settings
Packages/Default/Preferences (<platform>).sublime-settings
Packages/User/Preferences.sublime-settings
<Project Settings>
Packages/<syntax>/<syntax>.sublime-settings
Packages/User/<syntax>.sublime-settings
<Buffer Specific Settings>
```

Settings can be set on a per-project basis, details are in the [Project Documentation](https://www.sublimetext.com/docs/3/projects.html)
