### ISSUE TITLE
Global name `globmodule` not found

### ISSUE THREAD

**Issue by joeybaker** [TheSavior/ESLint-Formatter#15]
It looks like this line: https://github.com/TheSavior/ESLint-Formatter/blob/master/ESLint-Formatter.py#L171

is causing: ![](https://cloudup.com/cWxH39vJ0P0+)

**Comment by xwartz** [comment]
It's my mistake...

**Comment by TheSavior** [comment]
Thanks for the note. I apparently forgot to tag it via github releases. Should be fixed when packagecontrol runs their next update.

**Comment by joeybaker** [comment]
Thanks!
