### ISSUE TITLE
How can we update the key binding?

### ISSUE THREAD

**Issue by slashwhatever** [TheSavior/ESLint-Formatter#24]
What command do we need to add to our Key Bindings file to change the default keyboard shortcut?

**Comment by TheSavior** [comment]
![screen shot 2016-10-08 at 4 07 24 pm](https://cloud.githubusercontent.com/assets/249164/19216458/5380bbe8-8d71-11e6-9201-dc2d03a5c881.png)

**Comment by slashwhatever** [comment]
I should have been more clear - what's the **string we need to use for the command** in the key binding in order to update it?

I know where the key binding settings are in Sublime :)

**Comment by TheSavior** [comment]
Hmm. I'm still not sure what you are asking. Are you asking what the format is to specify the keys required to press? Like `super+6`?

**Comment by slashwhatever** [comment]
Sorry I'm not explaining myself very well :)

Here's and example keybinding for refreshing my folder list. I've set mine to "super+shift+r"

`{ "keys": ["super+shift+r"], "command": "refresh_folder_list" },`

In order to change the default key stroke for ESLint formatter, I don't know what the value of key "command" needs to be.

**Comment by TheSavior** [comment]
Gotcha. If you follow the key binding settings from my screenshot and click on `Key Bindings - Default`, the content of the default bindings is:

```
[{
  "keys": ["super+shift+h"],
  "command": "format_eslint"
}]
```

That is the command you are looking for.
