### ISSUE TITLE
fix .vue component files on save

### ISSUE THREAD

**Issue by xiaofan2406** [TheSavior/ESLint-Formatter#25]
any chance this plugin is planning to work with `.vue` files?

**Comment by TheSavior** [comment]
If you use this plugin via the hot keys with the `.vue` file open, it should work if it works with eslint's cli. 

If you want to use format on save then you need to update your user settings for this plugin.

**Comment by geoidesic** [comment]
Doesn't work for me. Hot key doesn't work even in normal js files (whereas the format on save does). Neither works for vue SFC files.
