### ISSUE TITLE
Windows: formatting removes the first 3 characters in the file

### ISSUE THREAD

**Issue by JQNinja** [TheSavior/ESLint-Formatter#27]
Whenever I use the formatter (either by using Ctrl+Shift+H or saving with "format_on_save" set to "true") the first three characters in the file get removed. Looking at the console It appears to be happening after "reloading." 

Windows 8.1 Enterprise x64
Sublime Text 3, build 3126
ESLint-Formatter v2.2.1

Other Packages Installed...
Package Control v3.2.1
Babel v8.6.3
![win_first_3_chars_missing_after_reload](https://cloud.githubusercontent.com/assets/303104/19576036/b9abb8d0-96ce-11e6-8c0d-cc488b230816.png)

**Comment by TheSavior** [comment]
Hmm. Interesting. I've never run into this before so I'm not sure if it is windows specific. 

Can you confirm that running `eslint --fix YOUR/FILE/PATH.js` works from the command line?

**Comment by JQNinja** [comment]
D'oh! I'm really sorry. I can't reproduce this anymore. Faith healing strikes again.

**Comment by TheSavior** [comment]
Great, glad to hear!
