### ISSUE TITLE
Comments not re-indented properly

### ISSUE THREAD

**Issue by fastfedora** [TheSavior/ESLint-Formatter#28]
If I am converting from a file with 2 space indentation to 4 space indentation, all the code gets indented correctly, but comments remain at their original indentation.

For instance:

```
class {
  /**
   * My doc
   */
  execute() {
    // do something cool
    doSomething();
  }
}
```

gets reformatted into:

```
class {
  /**
   * My doc
   */
    execute() {
    // do something cool
      doSomething();
    }
}
```

when it should be:

```
class {
    /**
     * My doc
     */
    execute() {
      // do something cool
      doSomething();
    }
}
```

**Comment by TheSavior** [comment]
This sounds like an issue with eslint, the formatter just calls out to eslint.
