### ISSUE TITLE
Local config ignored if project contains multiple projects

### ISSUE THREAD

**Issue by zekedroid** [TheSavior/ESLint-Formatter#29]
My current setup is such that I have a single folder, called Projects, where I have all my JS repos. This is the folder I import into Sublime because I am constantly creating and deleting projects and like to avoid having to manually add projects to the sublime space.

Now each project has its own version of `eslint` and a `.eslintrc` file. In an instance of Sublime with one of these projects imported individually, the plugin works well. The problem is that when there is a high level folder containing them, the user settings for the formatter are ignored and it tries to default to the global settings, which fail. 

Not sure if this is a bug or intended. If intended, is there a way to override this behavior to allow the formatter to use local settings?

**Comment by TheSavior** [comment]
This is not intended behavior and I'd happily accept a pull request that improves local config detection. :+1:

**Comment by zekedroid** [comment]
Haha alright. I'm gonna try to find some time to make one (though could be a while). A good strategy will be to copy whatever `SublimeLinter-contrib-eslint` does because it manages to find the right `.eslintrc` file.
