### ISSUE TITLE
Not all fixes are applied at once - have to run tool several times to format code properly

### ISSUE THREAD

**Issue by Litee** [TheSavior/ESLint-Formatter#3]
Hi, 

First of all - thanks for the plugin, very promising. Do far I have noticed a problem - when there are several problems in my code I have to repeat Ctrl-Shift-H several times to get the desired effect. It looks like errors are fixed one by one, not all-at-once.

**Comment by TheSavior** [comment]
This plugin just runs the ESLint --fix command. If you try running the command manually from the command line, do you see the same behavior? If so, feel free to open a ticket on ESLint's project. If not, feel free to reopen this ticket and we can take a closer look.

**Comment by Litee** [comment]
I think you are right - same behavior when running from command-line.

**Comment by Litee** [comment]
As possible workaround - run --fix until file doesn't change
