### ISSUE TITLE
support set eslint options 

### ISSUE THREAD

**Issue by noyobo** [TheSavior/ESLint-Formatter#31]
like:

### Settings

```js
{
  // The Nodejs installation path
  "node_path": {
    "windows": "node.exe",
    "linux": "/usr/bin/nodejs",
    "osx": "/usr/local/bin/node"
  },
  "eslint_argv": ["--no-eslintrc"], // eslint options
  "config_path": "~/.eslintrc.js",
}
```

Because when your project has `.eslinrc` file and  set up `config_path`, You must set `--no-eslintrc`.

**Comment by noyobo** [comment]
```
~/
 |-.eslintrc
 |----foo/
         |-.eslintrc
         |-index.js 
```

I want use the global `~/.eslintrc` config. but not `--no-eslintrc`, if you will format the `foo/index.js`, actually format by `foo/.eslintrc`

**Comment by TheSavior** [comment]
This should be the current behavior as of this PR a while back: https://github.com/TheSavior/ESLint-Formatter/pull/13
