### ISSUE TITLE
Does this also lint, or does it just format?

### ISSUE THREAD

**Issue by balupton** [TheSavior/ESLint-Formatter#41]
Would be nice if it mentioned this in the readme :)

**Comment by TheSavior** [comment]
This plugin is only a formatter. 

If the description on the readme wasn't clear enough, I'd happily accept a PR making it more clear for future people coming across the project.

For reference, this is the description on the readme.

```
Sublime Text 3 Plugin to autoformat your javascript code according to the ESLint configuration files you already have.
```
