### ISSUE TITLE
Formatting errors when ES6 present

### ISSUE THREAD

**Issue by rhlowe** [TheSavior/ESLint-Formatter#54]
Given a bit of code,

```js
var strings = [
    "double",
    'single',
];
```

ESLint-Formatter works just fine. However, given a bit of code with ES6 template strings or template literals, 

```js
var strings = [
    "double",
    'single',
    `templates`,
];
```

drops an error in the SublimeText console: "4:5  error  Parsing error: Unexpected character '`'"

Furthermore, I am noticing formatting errors with ES6 keywords, specifically `let` and `const`.

**Comment by skeggse** [comment]
This sounds like a misconfiguration in `eslint` itself - does it work if you run `eslint` with the same command from a shell?

**Comment by rhlowe** [comment]
I doubt this is still an issue, or at least it was an issue of me, mis-configured 2.5 years ago!
