### ISSUE TITLE
can not find module  '/usr/local/bin/eslint' - eslint_d

### ISSUE THREAD

**Issue by craigcosmo** [TheSavior/ESLint-Formatter#56]
Hi,

I installed `eslint_d` package in sublime. 
And then `npm i -g eslint_d` in terminal

And the set up this config in sublime

<img width="1439" alt="screen shot 2017-11-09 at 5 53 45 pm" src="https://user-images.githubusercontent.com/538657/32602038-3a0f692c-c577-11e7-9be8-592fd66cae21.png">

then try to format lint and I got this error

<img width="1065" alt="screen shot 2017-11-09 at 5 54 09 pm" src="https://user-images.githubusercontent.com/538657/32602055-46fe46a8-c577-11e7-9f54-0ce39116c215.png">

**Comment by cristianl** [comment]
To use a globally installed eslint_d, your user settings should be:
```json
{
  "local_eslint_path": {
    "osx": "node_modules/.bin/eslint_d"
  },
  "eslint_path": {
    "osx": "/usr/local/bin/eslint_d"
  },
  "format_on_save": false
}
```
By default, ESLint Formatter looks for the regular eslint, not eslint_d (in `/usr/local/bin/eslint` – line 25 in the left side panel). `"local_eslint_path"` applies only if you install eslint_d locally to your project (`npm install eslint_d`)

**Comment by TheSavior** [comment]
Thanks for that answer @cristianl.

I believe this is also mentioned in the README: https://github.com/TheSavior/ESLint-Formatter#performance

If the readme isn't clear about how to set this up, I'd be happy to accept a PR adding more information.
