### ISSUE TITLE
.eslintignore is not currently supported

### ISSUE THREAD

**Issue by franciscolourenco** [TheSavior/ESLint-Formatter#62]
"format_on_save" is currently ignoring the rules set in [`.eslintignore`](https://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories)

**Comment by slashwhatever** [comment]
Agree - this would be very helpful. We have a project that has a good chunk of legacy code that we don't want auto formatted any time someone updates a single line of code. Having to turn off ESLint-Formatter every time you edit one of these files is a pain.

**Comment by skeggse** [comment]
I was finding the same problem, and updated the logic we use to determine the current working directory:

https://github.com/TheSavior/ESLint-Formatter/blob/8000aa00909ea210f1b956a7c749a78f7bd960b3/ESLint-Formatter.py#L73-L80

This appears to have fixed the problem for me. Please reopen if this is still a problem!
