### ISSUE TITLE
Programmatically find Node and ESLint directory

### ISSUE THREAD

**Issue by tienthanh8490** [TheSavior/ESLint-Formatter#65]
Hi, I just tried your plugin and it works great. My only concern is that the directory for Node and ESLint is hardcoded into the settings which makes it inconvenient for nvm users who use a different directory. How about making it dynamic instead? I am asking since I faced the similar issue with plugins that depend on Node before, so I'm using a script which overrides the PATH to fix it. If you don't have time I'm always happy to help with PR.

**Comment by katerlouis** [comment]
also a nvm user here;
@tienthanh8490 did you make a pr yet? 
could you share your script overriding the PATH?

**Comment by skeggse** [comment]
In 2.4.0, you can specify `false` in the `local_eslint_path` and `node_path` objects, which let you use an arbitrary command that's available on the `PATH`. For example, if you want to use the globally available `eslint_d`:

```jsonc
{
  "node_path": {"linux": false},
  "eslint_path": {"linux": "eslint_d"},
  "local_eslint_path": {"linux": false},
  "format_on_save": true,
  "fix_to_stdout": true
}
```

If that doesn't fix your problem, please reopen!
