### ISSUE TITLE
reload on fix

### ISSUE THREAD

**Issue by ErAz7** [TheSavior/ESLint-Formatter#71]
Hey guys
Good job with your nice package

I have something that can bring an even better developer experience with this package (at least for me)
the issue is: when fix a file, it writes to file directly and this leads to sublime reload the file after fix which cause a blink and sometimes the scroll offset changes and these are something confusing and annoying
I was just wondering if you can improve this great package to work like prettier that only changes code in sublime and does not touch the file directly, then you can save it or do whatever you want, no blinks, no sudden scroll changes

**Comment by skeggse** [comment]
With #77, you can get around this by using `eslint_d`:

```json
{
  "node_path": {"linux": false},
  "eslint_path": {"linux": "eslint_d"},
  "local_eslint_path": {"linux": false},
  "format_on_save": true,
  "fix_to_stdout": true
}
```

A full fix will likely require #34, so I'm closing this issue in favor of tracking the work in that issue.
