### ISSUE TITLE
eslint command-line options support

### ISSUE THREAD

**Issue by rosedo** [TheSavior/ESLint-Formatter#74]
Since ESLint 7.0.0 (very recent) I had to change SublimeLinter configuration to resolve plugins globally.

Example configuration for SublimeLinter:
`"executable": ["eslint", "--resolve-plugins-relative-to", "%APPDATA%/npm"]`

This runs `eslint --resolve-plugins-relative-to "%APPDATA%/npm" <file>`

On linux it could be `eslint --resolve-plugins-relative-to "$(dirname "$(npm root -g)")"`
or more simply `eslint --resolve-plugins-relative-to /usr/lib`

I tried to configure ESLint-Formatter but it doesn't accept command-line options.

**Comment by skeggse** [comment]
Not sure if it's been published, but would this be fixed by #72?

**Comment by rosedo** [comment]
Yes thanks I forgot to upgrade the ESLint-Formatter package.

`"extra_args": ["--resolve-plugins-relative-to", "%APPDATA%/npm"]`
