### ISSUE TITLE
Error panel popping  on save 

### ISSUE THREAD

**Issue by im-sunil** [TheSavior/ESLint-Formatter#79]
sublime linter  "show_panel_on_save": "never", 

![image](https://user-images.githubusercontent.com/6269292/82476644-03818280-9aec-11ea-966c-aa2f85254f74.png)

**Comment by skeggse** [comment]
I ran into this once, but wasn't able to reproduce this. Can you try #80 and see if that fixes it? Easiest way to test is to copy the file to a new `Packages/ESLint-Formatter` directory in your sublime configuration directory: https://packagecontrol.io/docs/customizing_packages#Overrides.

**Comment by vietvu-nguyen** [comment]
@skeggse it works. Pop-ups stop appearing with [#80](https://github.com/TheSavior/ESLint-Formatter/pull/80)

**Comment by skeggse** [comment]
Fix released in 2.4.2, which may take a bit for package control to find and distribute.

**Comment by im-sunil** [comment]
Ok thanks
