### ISSUE TITLE
Vue SFC Error

### ISSUE THREAD

**Issue by conantp** [TheSavior/ESLint-Formatter#81]
Since updating to 2.4.1, I get an error working in Vue single file components.

1:1  error  Parsing error: Unexpected token <

✖ 1 problem (1 error, 0 warnings)

It's highlighting the <template> tag at the top of the file.

**Comment by skeggse** [comment]
This sounds like #79. Fix is out in 2.4.2. Please re-open and provide additional diagnostic information if your problem persists after upgrading.
