### ISSUE TITLE
format_on_save: true doesn't work

### ISSUE THREAD

**Issue by fabioguarrasi** [TheSavior/ESLint-Formatter#9]

**Comment by TheSavior** [comment]
What does "not work" mean? What is the file name of the file you are saving? Only some file extensions are formatted when using that option.

**Comment by glockjt** [comment]
.js files will not format.

**Comment by TheSavior** [comment]
What do your plugin settings look like? Please see the section in the README about formatting on save file extensions

**Comment by xwartz** [comment]
``` format_on_save: true ``` 
when saving it doesn't work, but  using Command Palette worked well.

**Comment by TheSavior** [comment]
This should be fixed in 2.0.1 per #14

**Comment by hi-hai** [comment]
Still not work per my test.

**Comment by hi-hai** [comment]
nvm. It works. Need to specify my .tsx filename.
